### ISSUE TITLE
Trying to add new group without logging in throws an Exception

### ISSUE THREAD

**Issue by tomfor** [codelathe/filecloudapi-php#5]
This happens in the Collection, which expects a valid XML string to be passed. When it's not valid an exception is thrown in line 89 when the SimpleXMLElement is created.

**Comment by jefersonralmeida** [comment]
Fixed on v1.0.2.

**Comment by tomfor** [comment]
This wasn't fixed yet.

**Comment by jefersonralmeida** [comment]
@czarpino is it fixed on v1.0.3? Please confirm and close the issue.

**Comment by czarpino** [comment]
@jefersonralmeida Sorry for the confusion. That was an unrelated commit message with the string `#5` that GitHub interpreted as a reference to this ticket. As far as we're concerned, this issue is still wide open.
